- ui/tests/test_forms.py
- ui/tests/test_views.py
- ui/views.py
Oops. Also added the following to my pre-commit githook:
```sh
#!/bin/sh
flake8 --exclude=migrations --ignore=E501 $(git status -s | grep -E '\.py$' | cut -c 4-)
```
This will run flake8 on all changed files.
> Fix linting

- docker-entrypoint.sh
- gunicorn/conf.py
- makefile
https://uktrade.atlassian.net/browse/ED-148
> Update config for deployment to dev Heroku environment

- .gitignore
- ui/static/sass/main.scss
- ui/templates/form-wrapper.html
- ui/templates/govuk_layout.html
- ui/templates/registered.html
Recovery of [this branch](https://github.com/uktrade/directory-ui/pull/16)
[this task](https://uktrade.atlassian.net/browse/ED-127)
- fixed styling for registered and thank you page
- fixed anchor tag link styling
- tidy up
> Form accessibility part1

- registration/forms.py
- registration/templates/company-profile-updated.html
- registration/views.py
- ui/tests/company_profile/test_forms.py
- ui/urls.py
Adds:
- View for basic company info edit
- The form
- Unit tests for the form validation
> Add company profile basic info edit view

- package.json
- scripts/sass.sh
The sass commands have reached 350 characters, so hard to maintain.
> Add scss compilation script to be DRYer

- registration/forms.py
- registration/templates/company-profile-form.html
- registration/tests/test_forms.py
- registration/tests/test_templates.py
- registration/tests/test_validators.py
- registration/validators.py
- registration/views.py
- ui/settings.py
[this task](https://uktrade.atlassian.net/browse/ED-140)
> Company profile logo field

- registration/tests/test_views.py
- registration/views.py
[this task](https://uktrade.atlassian.net/browse/ED-177)
> Retrieve company details from API

- README.md
- circle.yml
- env.json
- makefile
- registration/tests/test_views.py
- registration/views.py
https://uktrade.atlassian.net/browse/ED-63
> Add debug env, namespace docker commands in makefile

- registration/forms.py
- ui/urls.py
- user/forms.py
- user/templates/user-profile-form.html
- user/templates/user-profile-update-error.html
- user/tests/test_forms.py
- user/tests/test_views.py
- user/views.py
[this task](https://uktrade.atlassian.net/browse/ED-227)
> Add user profile edit page

- enrolment/static/sass/enrolment.scss
- enrolment/static/sass/main.scss
- enrolment/templates/govuk_layout.html
- enrolment/templates/header.html
- enrolment/templates/hero-sub-header.html
part of [this task](https://uktrade.atlassian.net/browse/ED-232)
Look at the subheader:
> Add hero sub header to base template

- README.md
- enrolment/clients/directory_api.py
- enrolment/tests/test_views.py
- enrolment/views.py
- makefile
- requirements.txt
- ui/settings.py
- user/tests/test_views.py
- user/views.py
note we will now need to set env variables for `API_CLIENT_API_KEY` and `API_CLIENT_BASE_URL`
> Plug in the directory-api-client

- enrolment/forms.py
- enrolment/tests/test_forms.py
- enrolment/tests/test_validators.py
- enrolment/validators.py
- requirements.txt
[this task](https://uktrade.atlassian.net/browse/ED-249)
> Prevent same company registering twice

- docker-compose-test.yml
- makefile
Rename to enable tests running on https://hub.docker.com/r/ukti/directory-ui/
> Fix tests on docker hub

- docker/.env.test
- docker/env.json
- docker/env.test.json
- enrolment/static/sass/main.scss
- enrolment/templates/company-form.html
- enrolment/templates/form-wrapper.html
- enrolment/templates/header.html
- enrolment/templates/landing-page.html
- enrolment/tests/test_templates.py
- makefile
- requirements.txt
- sso/context_processors.py
- sso/tests/test_context_processors.py
- sso/utils.py
- ui/settings.py
> Show user as logged in or logged out depending on their sso user status

- enrolment/templates/company-profile-form.html
- enrolment/templates/form-wrapper.html
- enrolment/templates/landing-page.html
> Update landing page content and company profile edit

- enrolment/forms.py
- enrolment/templates/footer.html
- enrolment/templates/header.html
- enrolment/tests/test_forms.py
- enrolment/tests/test_validators.py
- enrolment/validators.py
- requirements.txt
> Add validation for if email addres already registered

- enrolment/forms.py
- enrolment/tests/test_forms.py
> Make form tests assertions more explicit

- enrolment/forms.py
[this bug](https://uktrade.atlassian.net/browse/ED-334)
> Fix typo on logo upload page

- enrolment/forms.py
- enrolment/tests/test_forms.py
[this task](https://uktrade.atlassian.net/browse/ED-338)
> Add help text to website field

- enrolment/helpers.py
- enrolment/tests/test_helpers.py
- enrolment/tests/test_views.py
- enrolment/views.py
[this task](https://uktrade.atlassian.net/browse/ED-355)
[needs this API change](https://github.com/uktrade/directory-api/pull/58)
> Check if company if verified when they view and edit their profile

- enrolment/forms.py
- enrolment/tests/test_forms.py
- requirements.txt
[this task](https://uktrade.atlassian.net/browse/ED-337)
[this task](https://uktrade.atlassian.net/browse/ED-336)
> Add keyword and sector choice limit validators

- enrolment/templates/google_tag_manager_head.html
The existing GTM snippet throws syntax error. This fixes it.
> Fix google tag manager

- enrolment/templates/landing-page-international.html
[this task] (https://uktrade.atlassian.net/browse/ED-403)
- heading now spans the container width of the international landing page
> heading styling stretched width of container

- enrolment/forms.py
#[this task](https://uktrade.atlassian.net/browse/ED-390)
> Improve help text of keywords form field

- enrolment/templates/company-profile-logo-form.html
[this task](https://uktrade.atlassian.net/browse/ED-385)
> Improve logo upload page title

- enrolment/templates/footer.html
[this task] (https://uktrade.atlassian.net/browse/ED-401)
- changed url for contact us
- changed text from "Contact" to "Contact Us"
> changed contact us url

- enrolment/templates/landing-page-international.html
[this task] (https://uktrade.atlassian.net/browse/ED-404)
- title changed on international landing page only
> changed title on international landing page

- enrolment/templates/govuk_layout.html
[this task](https://uktrade.atlassian.net/browse/ED-379)
> Remove cookie message

- enrolment/forms.py
- enrolment/tests/test_forms.py
[this task](https://uktrade.atlassian.net/browse/ED-409)
> Add link to "create a new code"

- enrolment/templates/landing-page-international-success.html
[this task](https://uktrade.atlassian.net/browse/ED-405)
> Update content of international landing success page

- enrolment/forms.py
- enrolment/tests/test_forms.py
https://uktrade.atlassian.net/browse/ED-408
> Change terms & conditions validation message

- enrolment/forms.py
https://uktrade.atlassian.net/browse/ED-389
Great if whoever is reviewing this can confirm I changed the right thing. The ticket wasn't 100% clear to me.
> Change company size help text

- enrolment/templates/landing-page-international-success.html
[this task](https://uktrade.atlassian.net/browse/ED-405)
> Change British to UK given guidance from content

- enrolment/forms.py
https://uktrade.atlassian.net/browse/ED-393
> Change company name form label

- enrolment/forms.py
- enrolment/tests/test_forms.py
- enrolment/tests/test_views.py
- enrolment/views.py
- makefile
[this task](https://uktrade.atlassian.net/browse/ED-415)
requires [this API change](https://github.com/uktrade/directory-api/pull/65)
> Pre-fill company profile edit page

- enrolment/constants.py
- enrolment/templates/export-status-form.html
- enrolment/templates/footer.html
- enrolment/templates/header.html
- enrolment/tests/test_urls.py
- enrolment/tests/test_views.py
- enrolment/views.py
- ui/urls.py
[this task](https://uktrade.atlassian.net/browse/ED-416)
We will need to do a similar thing for `directory-sso`. In a follow up PR I will make these external urls a different repo that both can share.
> Make external urls more maintainable

- enrolment/templates/sms-verify-form.html
[this task](https://uktrade.atlassian.net/browse/ED-342)
> Update label on sms verification form

- enrolment/fields.py
- enrolment/forms.py
- enrolment/tests/test_fields.py
- enrolment/tests/test_forms.py
- enrolment/tests/test_views.py
- makefile
- requirements.txt
[this task](https://uktrade.atlassian.net/browse/ED-438)
> Add validation to mobile phone number field

- enrolment/templates/footer.html
- requirements.txt
[this task](https://uktrade.atlassian.net/browse/ED-442)
[relies on this pr](https://github.com/uktrade/directory-constants/pull/3)
> Update the footer logo link

- enrolment/templates/landing-page.html
[this task](https://uktrade.atlassian.net/browse/ED-430)
> Remove ellipsis from landing page

- company/helpers.py
- company/templates/company-profile-detail.html
- company/templates/company-public-profile-list.html
- company/tests/test_helpers.py
- company/tests/test_templates.py
- company/tests/test_views.py
- company/views.py
- enrolment/tests/test_templates.py
- requirements.txt
- ui/urls.py
[this task](https://uktrade.atlassian.net/browse/ED-467)
[this task](https://uktrade.atlassian.net/browse/ED-160)
[this task](https://uktrade.atlassian.net/browse/ED-159)
> Add public company profile and list views

- company/templates/company-public-profile-list.html
- company/tests/test_templates.py
[this task](https://uktrade.atlassian.net/browse/ED-496)
> Replace supplier external url with 'view profile'

- company/helpers.py
- company/templates/company-profile-detail.html
- company/templates/company-public-profile-list.html
- company/tests/test_helpers.py
- company/tests/test_templates.py
- company/tests/test_views.py
- company/views.py
- ui/context_processors.py
- ui/settings.py
- ui/tests/test_context_processors.py
[this task](https://uktrade.atlassian.net/browse/ED-498)
> Add links to supplier list filtered by sector

- company/conftest.py
- company/forms.py
- company/tests/test_forms.py
- company/tests/test_views.py
- company/views.py
- enrolment/helpers.py
- enrolment/tests/test_helpers.py
> Populate company contact details and prevent tamper

- company/conftest.py
- company/forms.py
- company/helpers.py
- company/templates/company-profile-detail.html
- company/tests/test_forms.py
- company/tests/test_views.py
- company/views.py
- enrolment/templates/form-wrapper.html
- ui/urls.py
[this task](https://uktrade.atlassian.net/browse/ED-547)
> Standalone profile edit pages

- company/forms.py
- company/templates/company-profile-detail.html
- company/tests/test_forms.py
- company/tests/test_templates.py
- company/tests/test_views.py
- company/views.py
[this task](https://uktrade.atlassian.net/browse/ED-546)
> Present wizard profile edit view if profile empty

- company/forms.py
- company/tests/test_forms.py
- company/tests/test_views.py
[this task](https://uktrade.atlassian.net/browse/ED-581)
> Remove mobile phone field from contact details
